env: prod

logger:
  env: prod  # prod или dev отвечает за уровень логирования

db:
  dsn: "tests/database/example.db"
  migration_path: "migrations/"

ui:
  name: "burovichok"
  width: 1000
  height: 600
