name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.5'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          software-properties-common \
          && sudo add-apt-repository universe \
          && sudo add-apt-repository multiverse \
          && sudo apt-get update \
          && sudo apt-get install -y \
          libgl1-mesa-dev \
          libgtk-3-dev \

      - name: Install dependencies
        run: go mod tidy

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run tests
        run: go test ./...

      - name: Check code style
        run: gofmt -l -s .

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Run golint
        run: golint ./...
